local_backend: false
# Decap CMS config for GitHub backend on Cloudflare Pages
backend:
  name: github
  repo: nguyen1357/NIO-Lab-Website
  branch: main
  auth_type: implicit                    # dùng OAuth App của GitHub
  # Sau khi trỏ domain, tạo GitHub OAuth App:
  # - Homepage URL: https://<your-domain>
  # - Authorization callback URL: https://<your-domain>/admin/callback

media_folder: "public/uploads"           # nơi lưu file media trong repo
public_folder: "/uploads"                # URL khi truy cập từ web

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Type", name: "type", widget: "select", options: ["News", "Event", "Update"] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "External Link", name: "link", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
